### ISSUE TITLE
FindOne or FindAll function problem

### ISSUE THREAD

**Issue by devcrazygit** [goonode/mogo#1]
Thank you for your great framework. It's useful. But I have one problem.
Could you wrap mgo's Find function? It returns error if there's no document and maybe it is ErrNotFound. I think it is confusing if it has a database problem or ErrNotFound problem. To determine, I have to check it's type. It is slightly annoying. I think it may return **result** as nil if there's no document from query and **err** as nil. Thank you again.

**Comment by goonode** [comment]
But it is already a wrapper to the mgo's Find func. Did you mean to change the mgo's Find behavior?  I think, It should be more simple to manage it with a func in your code, instead.
